### ISSUE TITLE
Long field-description text is too confined.

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#31]
The field description on the MetadataBrowse config page for global settings is unnecessarily constricted horizontally. Looks like style should override the CSS from core for this one.

![mbglobalconfig](https://user-images.githubusercontent.com/153262/28998229-dee16e2a-79f3-11e7-9622-7f7e1746f44c.png)

**Comment by patrickmj** [comment]
@kimisgold looks like I'm going to need your expertise on this one. Current develop blots out all my module-specific hijinks. I haven't found what style and/or HTML structure keep that long text constrained.

**Comment by kimisgold** [comment]
This strikes me as an edge case where we have a checkbox with a long label and even more verbose description. I have some ideas:

1. Target that specific row's `.inputs` container, and set `min-width: 0`. That should allow the text to span the full-width, but to be honest, it looks awkward to me how much the text engulfs the checkbox. It also looks odd as no other field row in the admin currently diverges from the default proportions.

<img width="701" alt="screen shot 2017-08-16 at 4 38 57 pm" src="https://user-images.githubusercontent.com/606764/29384332-b1bb7286-82a1-11e7-9e3e-9e81bb2055b4.png">

2. Make the description shorter and include a link out to documentation more fully explaining the setting.

3. Move the long description outside and above the row. I'm leaning towards this one so that the checkbox has room to breathe. That setting also seems to require more explanation and contextualization than the field description was built to accommodate, as it's supposed to be the equivalent of a tooltip.

<img width="705" alt="screen shot 2017-08-16 at 4 50 10 pm" src="https://user-images.githubusercontent.com/606764/29384712-1bbdd326-82a3-11e7-8081-968fff82954e.png">
